replicaCount: 1
image:
  repository: r.cfcr.io/lfurrea/k8swordsmithdemo
  tag: development-87f6e0b
  pullPolicy: IfNotPresent
nameOverride: ""
fullnameOverride: ""
service:
  type: NodePort
  port: 80
ingress:
  enabled: false
  annotations: {}
  paths: []
  hosts:
  - chart-example.local
  tls: []
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
